version: '2.2'
services:
  api:
    restart: always
    build:
      context: ./producer
    ports:
      - 8080:8080
    depends_on:
      - redpanda
    command: 'producer'
  worker:
    restart: always
    build:
      context: ./consumer
    depends_on:
      - redpanda
    # command: 'python loop-graceful-shutdown.py'
    command: 'python batching-graceful-shutdown.py'
  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --memory 
    - 1G
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:latest 
    container_name: redpanda-1
    ports:
    - 9092:9092
    - 29092:29092
